project:
  type: website

website:
  title: "Han Sun"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        href: about.qmd
      - text: "Activity"
        menu:
          - text: "Activity 1"
            href: activity/activity1/file_org_activity/code/clean/cleaning.qmd
          - text: "Activity 2"
            href: activity/03-adv-ggplot-notes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

